// <auto-generated />
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Backend.Migrations
{
    [DbContext(typeof(ProdutoContext))]
    [Migration("20210301213435_add-migratio Inicial")]
    partial class addmigratioInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Backend.Models.ProdutoModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<decimal>("Preco")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Nome = "Produto A",
                            Preco = 9.00m
                        },
                        new
                        {
                            Id = 2L,
                            Nome = "Produto B",
                            Preco = 5.00m
                        },
                        new
                        {
                            Id = 3L,
                            Nome = "Produto C",
                            Preco = 15.00m
                        },
                        new
                        {
                            Id = 4L,
                            Nome = "Produto D",
                            Preco = 16.00m
                        },
                        new
                        {
                            Id = 5L,
                            Nome = "Produto E",
                            Preco = 17.00m
                        },
                        new
                        {
                            Id = 6L,
                            Nome = "Produto F",
                            Preco = 18.00m
                        },
                        new
                        {
                            Id = 7L,
                            Nome = "Produto G",
                            Preco = 19.00m
                        },
                        new
                        {
                            Id = 8L,
                            Nome = "Produto H",
                            Preco = 20.00m
                        },
                        new
                        {
                            Id = 9L,
                            Nome = "Produto I",
                            Preco = 21.00m
                        },
                        new
                        {
                            Id = 10L,
                            Nome = "Produto J",
                            Preco = 22.00m
                        },
                        new
                        {
                            Id = 11L,
                            Nome = "Produto K",
                            Preco = 23.00m
                        },
                        new
                        {
                            Id = 12L,
                            Nome = "Produto L",
                            Preco = 24.00m
                        },
                        new
                        {
                            Id = 13L,
                            Nome = "Produto M",
                            Preco = 25.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
